DROP DATABASE tacos_db;
CREATE DATABASE tacos_db;
USE tacos_db;

CREATE TABLE tacos (
	id INT NOT NULL AUTO_INCREMENT,
	taco_name VARCHAR(100) NOT NULL,
	devoured BOOLEAN DEFAULT false,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);